export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_ERRORS = 'SET_SIGNUP_ERRORS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const GET_USER_FOLLOWINGS = 'GET_USER_FOLLOWINGS';
export const SET_USER_FOLLOWINGS = 'SET_USER_FOLLOWINGS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const CLEAR = 'CLEAR';
