export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_ERRORS = 'SET_SIGNUP_ERRORS';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const SET_USER_FOLLOWINGS = 'SET_USER_FOLLOWINGS';
